# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@v1.6.1
      with:
          kernel-url: https://github.com/MiCode/Xiaomi_Kernel_OpenSource
          kernel-dir: sheng-u-oss
          kernel-branch: sheng-u-oss
          config: build.config.msm.sheng
          depth: 1
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          # set any version you want
          ksu-version: v1.0.0
          # use empty verson, fix for clang downloading 400
          android-version: ''
          aosp-clang-version: r522817
          python-27: true
          disable-lto: true
          anykernel3: true
          # enable lxc 
          lxc: true
          lxc-patch: true
          kvm: true

          # release
          release: true
          access-token: ${{ github.token }}
