# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: kiritoxkiriko/kernel_build_action@main
      with:
          build-gki: true
          kernel-url: "https://github.com/MiCode/Xiaomi_Kernel_OpenSource"
          #kernel-url: "https://android.googlesource.com/kernel/manifest"
          #kernel-dir: sheng-u-oss
          #kernel-branch: sheng-u-oss
          kernel-branch: common-android13-5.15-2023-11
          config: defconfig
          depth: 1
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-lkm: true
          # set any version you want
          ksu-version: v1.0.0

          # use empty verson, fix for clang downloading 400
          android-version: ''
          aosp-clang-version: r522817
          #aosp-clang-version: r475365b
          #python-27: true
          python-27: false
          disable-lto: false
          anykernel3: true
          # enable lxc 
          lxc: true
          lxc-patch: true
          kvm: true
          # pre-build
          #pre-build-script: "https://github.com/kiritoxkiriko/build-android-kernel/raw/main/pre-build.sh"

          # release
          release: true
          access-token: ${{ github.token }}
